# generated by Neptune Namespaces
# file: art/flux/parse/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Parse ||
class Flux.Parse extends Neptune.Base
  @namespace: Flux
  @namespacePath: "Neptune.Art.Flux.Parse"

Flux.addNamespace Flux.Parse