# generated by Neptune Namespaces v0.5
# file: art/flux/parse/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Parse ||
Flux.addNamespace 'Parse', class Parse extends Neptune.Base
  ;